spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: false
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  #    hibernate:
  #      ddl-auto: validate

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:./db/address_book
    username: sa
    password:
    driverClassName: org.h2.Driver

server:
  port: 8080
